#pragma once
#define BRAINCLOUD_SERVER_URL "https://api.internal.braincloudservers.com/dispatcherv2"
#define BRAINCLOUD_APP_ID "20001"
#define BRAINCLOUD_APP_SECRET "4e51b45c-030e-4f21-8457-dc53c9a0ed5f"
#define BRAINCLOUD_APP_VERSION "1.0"
#define BRAINCLOUD_CHILD_APP_ID ""
#define BRAINCLOUD_CHILD_APP_SECRET ""
#define BRAINCLOUD_PARENT_LEVEL_NAME "Master"
#define BRAINCLOUD_PEER_NAME "peerapp"
#define BRAINCLOUD_SERVER_NAME "TestServer"
#define BRAINCLOUD_SERVER_SECRET ""
#define BRAINCLOUD_S2S_SERVER "https://sharedprod.braincloudservers.com/s2sdispatcher"
#define TESTFILE_SERVER_URL ""
#define TESTFILE_APP_ID ""
#define TESTFILE_APP_SECRET ""
