#if defined(__ANDROID__)

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bitheads_braincloud_AndroidBridge */

#ifndef _Included_com_bitheads_braincloud_AndroidBridge
#define _Included_com_bitheads_braincloud_AndroidBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bitheads_braincloud_AndroidBridge
 * Method:    setCountryCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_bitheads_braincloud_AndroidBridge_setCountryCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_bitheads_braincloud_AndroidBridge
 * Method:    setLanguageCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_bitheads_braincloud_AndroidBridge_setLanguageCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_bitheads_braincloud_AndroidBridge
 * Method:    setTimezoneOffset
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_bitheads_braincloud_AndroidBridge_setTimezoneOffset
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif

#endif
